language: java
jdk:
  - oraclejdk8
sudo: required
env: JAVADOC=true
dist: trusty
addons:
  chrome: stable
install: 
  - wget -N http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip
  - unzip -a chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - mv -f chromedriver driver/.
script:
  - mvn clean install
